# Generated by Django 3.2.6 on 2021-09-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukutamu', '0004_alter_bukutamu_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukutamu',
            name='keperluan_lainnya',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='keperluan',
            field=models.CharField(choices=[('Kunjungan', 'Kunjungan'), ('Magang', 'Magang'), ('Permohonan Informasi', 'Permohonan Informasi'), ('Lainnya', 'Lainnya')], max_length=100),
        ),
    ]
